[2024-03-25T00:50:07.251+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Book-Recommendation-DAG.do_clean_to_parquet_task manual__2024-03-25T00:47:54.835920+00:00 [queued]>
[2024-03-25T00:50:07.256+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Book-Recommendation-DAG.do_clean_to_parquet_task manual__2024-03-25T00:47:54.835920+00:00 [queued]>
[2024-03-25T00:50:07.257+0000] {taskinstance.py:2193} INFO - Starting attempt 3 of 3
[2024-03-25T00:50:07.264+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): do_clean_to_parquet_task> on 2024-03-25 00:47:54.835920+00:00
[2024-03-25T00:50:07.271+0000] {standard_task_runner.py:60} INFO - Started process 2476 to run task
[2024-03-25T00:50:07.274+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'Book-Recommendation-DAG', 'do_clean_to_parquet_task', 'manual__2024-03-25T00:47:54.835920+00:00', '--job-id', '30', '--raw', '--subdir', 'DAGS_FOLDER/book-recommendation-dag.py', '--cfg-path', '/tmp/tmpy9kac1j0']
[2024-03-25T00:50:07.277+0000] {standard_task_runner.py:88} INFO - Job 30: Subtask do_clean_to_parquet_task
[2024-03-25T00:50:07.316+0000] {task_command.py:423} INFO - Running <TaskInstance: Book-Recommendation-DAG.do_clean_to_parquet_task manual__2024-03-25T00:47:54.835920+00:00 [running]> on host 9654d883592e
[2024-03-25T00:50:07.376+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='iamraphson' AIRFLOW_CTX_DAG_ID='Book-Recommendation-DAG' AIRFLOW_CTX_TASK_ID='do_clean_to_parquet_task' AIRFLOW_CTX_EXECUTION_DATE='2024-03-25T00:47:54.835920+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-25T00:47:54.835920+00:00'
[2024-03-25T00:50:07.377+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/book-recommendation-dag.py", line 13, in do_clean_to_parquet
    for filename in os.listdir(dataset_download_path):
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/book-recommendation-dataset/'
[2024-03-25T00:50:07.384+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=Book-Recommendation-DAG, task_id=do_clean_to_parquet_task, execution_date=20240325T004754, start_date=20240325T005007, end_date=20240325T005007
[2024-03-25T00:50:07.391+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 30 for task do_clean_to_parquet_task ([Errno 2] No such file or directory: '/opt/airflow/book-recommendation-dataset/'; 2476)
[2024-03-25T00:50:07.419+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-25T00:50:07.433+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
