[2024-03-25T05:08:20.143+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Book-Recommendation-DAG.do_clean_to_parquet_task manual__2024-03-25T05:08:12.224331+00:00 [queued]>
[2024-03-25T05:08:20.150+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Book-Recommendation-DAG.do_clean_to_parquet_task manual__2024-03-25T05:08:12.224331+00:00 [queued]>
[2024-03-25T05:08:20.150+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 3
[2024-03-25T05:08:20.158+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): do_clean_to_parquet_task> on 2024-03-25 05:08:12.224331+00:00
[2024-03-25T05:08:20.165+0000] {standard_task_runner.py:60} INFO - Started process 6060 to run task
[2024-03-25T05:08:20.168+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'Book-Recommendation-DAG', 'do_clean_to_parquet_task', 'manual__2024-03-25T05:08:12.224331+00:00', '--job-id', '107', '--raw', '--subdir', 'DAGS_FOLDER/book-recommendation-dag.py', '--cfg-path', '/tmp/tmp3tjlbdih']
[2024-03-25T05:08:20.170+0000] {standard_task_runner.py:88} INFO - Job 107: Subtask do_clean_to_parquet_task
[2024-03-25T05:08:20.200+0000] {task_command.py:423} INFO - Running <TaskInstance: Book-Recommendation-DAG.do_clean_to_parquet_task manual__2024-03-25T05:08:12.224331+00:00 [running]> on host 9654d883592e
[2024-03-25T05:08:20.265+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='iamraphson' AIRFLOW_CTX_DAG_ID='Book-Recommendation-DAG' AIRFLOW_CTX_TASK_ID='do_clean_to_parquet_task' AIRFLOW_CTX_EXECUTION_DATE='2024-03-25T05:08:12.224331+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-25T05:08:12.224331+00:00'
[2024-03-25T05:08:22.402+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/book-recommendation-dag.py", line 61, in do_clean_to_parquet
    dataset_df[['city', 'state', 'country']] = pd.DataFrame(dataset_df['location_data'].tolist())
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/frame.py", line 3938, in __setitem__
    self._setitem_array(key, value)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/frame.py", line 3980, in _setitem_array
    check_key_length(self.columns, key, value)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/indexers/utils.py", line 392, in check_key_length
    raise ValueError("Columns must be same length as key")
ValueError: Columns must be same length as key
[2024-03-25T05:08:22.417+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=Book-Recommendation-DAG, task_id=do_clean_to_parquet_task, execution_date=20240325T050812, start_date=20240325T050820, end_date=20240325T050822
[2024-03-25T05:08:22.428+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 107 for task do_clean_to_parquet_task (Columns must be same length as key; 6060)
[2024-03-25T05:08:22.475+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-25T05:08:22.528+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
