[2024-03-25T05:06:32.842+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Book-Recommendation-DAG.do_clean_to_parquet_task manual__2024-03-25T05:06:24.959870+00:00 [queued]>
[2024-03-25T05:06:32.850+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Book-Recommendation-DAG.do_clean_to_parquet_task manual__2024-03-25T05:06:24.959870+00:00 [queued]>
[2024-03-25T05:06:32.850+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 3
[2024-03-25T05:06:32.860+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): do_clean_to_parquet_task> on 2024-03-25 05:06:24.959870+00:00
[2024-03-25T05:06:32.866+0000] {standard_task_runner.py:60} INFO - Started process 5973 to run task
[2024-03-25T05:06:32.869+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'Book-Recommendation-DAG', 'do_clean_to_parquet_task', 'manual__2024-03-25T05:06:24.959870+00:00', '--job-id', '104', '--raw', '--subdir', 'DAGS_FOLDER/book-recommendation-dag.py', '--cfg-path', '/tmp/tmpc0nkr_5l']
[2024-03-25T05:06:32.873+0000] {standard_task_runner.py:88} INFO - Job 104: Subtask do_clean_to_parquet_task
[2024-03-25T05:06:32.928+0000] {task_command.py:423} INFO - Running <TaskInstance: Book-Recommendation-DAG.do_clean_to_parquet_task manual__2024-03-25T05:06:24.959870+00:00 [running]> on host 9654d883592e
[2024-03-25T05:06:32.999+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='iamraphson' AIRFLOW_CTX_DAG_ID='Book-Recommendation-DAG' AIRFLOW_CTX_TASK_ID='do_clean_to_parquet_task' AIRFLOW_CTX_EXECUTION_DATE='2024-03-25T05:06:24.959870+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-25T05:06:24.959870+00:00'
[2024-03-25T05:06:35.419+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/book-recommendation-dag.py", line 59, in do_clean_to_parquet
    dataset_df['location_data'] = dataset_df['location'].str.split(',', expand=True).apply(lambda x: x.str.strip())
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/frame.py", line 3940, in __setitem__
    self._set_item_frame_value(key, value)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/frame.py", line 4094, in _set_item_frame_value
    raise ValueError(
ValueError: Cannot set a DataFrame with multiple columns to the single column location_data
[2024-03-25T05:06:35.453+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=Book-Recommendation-DAG, task_id=do_clean_to_parquet_task, execution_date=20240325T050624, start_date=20240325T050632, end_date=20240325T050635
[2024-03-25T05:06:35.466+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 104 for task do_clean_to_parquet_task (Cannot set a DataFrame with multiple columns to the single column location_data; 5973)
[2024-03-25T05:06:35.517+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-25T05:06:35.572+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
