[2024-03-25T19:35:54.887+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Book-Recommendation-DAG.do_upload_pq_to_gcs_task manual__2024-03-25T19:35:38.257151+00:00 [queued]>
[2024-03-25T19:35:54.892+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Book-Recommendation-DAG.do_upload_pq_to_gcs_task manual__2024-03-25T19:35:38.257151+00:00 [queued]>
[2024-03-25T19:35:54.893+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 3
[2024-03-25T19:35:54.898+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): do_upload_pq_to_gcs_task> on 2024-03-25 19:35:38.257151+00:00
[2024-03-25T19:35:54.904+0000] {standard_task_runner.py:60} INFO - Started process 313 to run task
[2024-03-25T19:35:54.906+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'Book-Recommendation-DAG', 'do_upload_pq_to_gcs_task', 'manual__2024-03-25T19:35:38.257151+00:00', '--job-id', '195', '--raw', '--subdir', 'DAGS_FOLDER/book-recommendation-dag.py', '--cfg-path', '/tmp/tmp09u54qpg']
[2024-03-25T19:35:54.908+0000] {standard_task_runner.py:88} INFO - Job 195: Subtask do_upload_pq_to_gcs_task
[2024-03-25T19:35:54.936+0000] {task_command.py:423} INFO - Running <TaskInstance: Book-Recommendation-DAG.do_upload_pq_to_gcs_task manual__2024-03-25T19:35:38.257151+00:00 [running]> on host 3bba2199f4f9
[2024-03-25T19:35:54.975+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='iamraphson' AIRFLOW_CTX_DAG_ID='Book-Recommendation-DAG' AIRFLOW_CTX_TASK_ID='do_upload_pq_to_gcs_task' AIRFLOW_CTX_EXECUTION_DATE='2024-03-25T19:35:38.257151+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-25T19:35:38.257151+00:00'
[2024-03-25T19:35:54.990+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/book-recommendation-dag.py", line 114, in do_upload_pq_to_gcs
    dir_info = gcs.get_file_info(gcs_pq_store_path)
  File "pyarrow/_fs.pyx", line 581, in pyarrow._fs.FileSystem.get_file_info
  File "pyarrow/error.pxi", line 154, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow/error.pxi", line 91, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: Path cannot start with a separator ('/book-recommendation-pq')
[2024-03-25T19:35:54.995+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=Book-Recommendation-DAG, task_id=do_upload_pq_to_gcs_task, execution_date=20240325T193538, start_date=20240325T193554, end_date=20240325T193554
[2024-03-25T19:35:55.002+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 195 for task do_upload_pq_to_gcs_task (Path cannot start with a separator ('/book-recommendation-pq'); 313)
[2024-03-25T19:35:55.049+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-25T19:35:55.072+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
