[2024-03-25T19:48:12.803+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Book-Recommendation-DAG.do_upload_pq_to_gcs_task manual__2024-03-25T19:47:59.820704+00:00 [queued]>
[2024-03-25T19:48:12.817+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Book-Recommendation-DAG.do_upload_pq_to_gcs_task manual__2024-03-25T19:47:59.820704+00:00 [queued]>
[2024-03-25T19:48:12.818+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 3
[2024-03-25T19:48:12.828+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): do_upload_pq_to_gcs_task> on 2024-03-25 19:47:59.820704+00:00
[2024-03-25T19:48:12.838+0000] {standard_task_runner.py:60} INFO - Started process 564 to run task
[2024-03-25T19:48:12.841+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'Book-Recommendation-DAG', 'do_upload_pq_to_gcs_task', 'manual__2024-03-25T19:47:59.820704+00:00', '--job-id', '199', '--raw', '--subdir', 'DAGS_FOLDER/book-recommendation-dag.py', '--cfg-path', '/tmp/tmpvk06ptly']
[2024-03-25T19:48:12.844+0000] {standard_task_runner.py:88} INFO - Job 199: Subtask do_upload_pq_to_gcs_task
[2024-03-25T19:48:12.870+0000] {task_command.py:423} INFO - Running <TaskInstance: Book-Recommendation-DAG.do_upload_pq_to_gcs_task manual__2024-03-25T19:47:59.820704+00:00 [running]> on host 3bba2199f4f9
[2024-03-25T19:48:12.907+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='iamraphson' AIRFLOW_CTX_DAG_ID='Book-Recommendation-DAG' AIRFLOW_CTX_TASK_ID='do_upload_pq_to_gcs_task' AIRFLOW_CTX_EXECUTION_DATE='2024-03-25T19:47:59.820704+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-25T19:47:59.820704+00:00'
[2024-03-25T19:48:12.913+0000] {logging_mixin.py:188} INFO - gcs_pq_store_path /book-recommendation-pq
[2024-03-25T19:48:12.913+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/book-recommendation-dag.py", line 114, in do_upload_pq_to_gcs
    dir_info = gcs.get_file_info(gcs_pq_store_path)
  File "pyarrow/_fs.pyx", line 581, in pyarrow._fs.FileSystem.get_file_info
  File "pyarrow/error.pxi", line 154, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow/error.pxi", line 91, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: Path cannot start with a separator ('/book-recommendation-pq')
[2024-03-25T19:48:12.918+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=Book-Recommendation-DAG, task_id=do_upload_pq_to_gcs_task, execution_date=20240325T194759, start_date=20240325T194812, end_date=20240325T194812
[2024-03-25T19:48:12.924+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 199 for task do_upload_pq_to_gcs_task (Path cannot start with a separator ('/book-recommendation-pq'); 564)
[2024-03-25T19:48:12.943+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-25T19:48:12.958+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
