[2024-03-26T01:49:37.898+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Book-Recommendation-DAG.create_table_partitions_task manual__2024-03-26T01:49:19.111858+00:00 [queued]>
[2024-03-26T01:49:37.903+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Book-Recommendation-DAG.create_table_partitions_task manual__2024-03-26T01:49:19.111858+00:00 [queued]>
[2024-03-26T01:49:37.904+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 3
[2024-03-26T01:49:37.910+0000] {taskinstance.py:2217} INFO - Executing <Task(BigQueryInsertJobOperator): create_table_partitions_task> on 2024-03-26 01:49:19.111858+00:00
[2024-03-26T01:49:37.914+0000] {standard_task_runner.py:60} INFO - Started process 3265 to run task
[2024-03-26T01:49:37.916+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'Book-Recommendation-DAG', 'create_table_partitions_task', 'manual__2024-03-26T01:49:19.111858+00:00', '--job-id', '328', '--raw', '--subdir', 'DAGS_FOLDER/book-recommendation-dag.py', '--cfg-path', '/tmp/tmpnspmf9_k']
[2024-03-26T01:49:37.918+0000] {standard_task_runner.py:88} INFO - Job 328: Subtask create_table_partitions_task
[2024-03-26T01:49:37.943+0000] {task_command.py:423} INFO - Running <TaskInstance: Book-Recommendation-DAG.create_table_partitions_task manual__2024-03-26T01:49:19.111858+00:00 [running]> on host 992e1288d09b
[2024-03-26T01:49:37.987+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='iamraphson' AIRFLOW_CTX_DAG_ID='Book-Recommendation-DAG' AIRFLOW_CTX_TASK_ID='create_table_partitions_task' AIRFLOW_CTX_EXECUTION_DATE='2024-03-26T01:49:19.111858+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-26T01:49:19.111858+00:00'
[2024-03-26T01:49:37.989+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2024-03-26T01:49:37.989+0000] {connection.py:269} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-03-26T01:49:37.990+0000] {base.py:83} INFO - Using connection ID 'google_cloud_default' for task execution.
[2024-03-26T01:49:37.990+0000] {credentials_provider.py:353} INFO - Getting connection using `google.auth.default()` since no explicit credentials are provided.
[2024-03-26T01:49:38.040+0000] {bigquery.py:2811} INFO - Executing: {'query': {'query': 'DROP TABLE IF EXISTS `book_recommendation_analytics.books`;\n\nCREATE TABLE IF NOT EXISTS\n  `book_recommendation_analytics.books`\nPARTITION BY DATE_TRUNC(years_of_publication, YEAR)\nCLUSTER BY\n  `years_of_publication`,\n  `publisher`,\n  `book_author` AS\nSELECT\n  *\nFROM\n  `book_recommendataion_wh.books`;', 'useLegacySql': False}}'
[2024-03-26T01:49:38.042+0000] {bigquery.py:1613} INFO - Inserting job ***_Book_Recommendation_DAG_create_table_partitions_task_2024_03_26T01_49_19_111858_00_00_b15e6335484ec3e825412df4570fa29f
[2024-03-26T01:49:39.911+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 2870, in execute
    job.result(timeout=self.result_timeout, retry=self.result_retry)
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/bigquery/job/query.py", line 1595, in result
    do_get_result()
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/bigquery/job/query.py", line 1584, in do_get_result
    super(QueryJob, self).result(retry=retry, timeout=timeout)
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/bigquery/job/base.py", line 971, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/google/api_core/future/polling.py", line 261, in result
    raise self._exception
google.api_core.exceptions.BadRequest: 400 Query error: Unrecognized name: years_of_publication; Did you mean year_of_publication? at [5:25]

Location: us-west1
Job ID: airflow_Book_Recommendation_DAG_create_table_partitions_task_2024_03_26T01_49_19_111858_00_00_b15e6335484ec3e825412df4570fa29f

[2024-03-26T01:49:39.951+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=Book-Recommendation-DAG, task_id=create_table_partitions_task, execution_date=20240326T014919, start_date=20240326T014937, end_date=20240326T014939
[2024-03-26T01:49:39.962+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 328 for task create_table_partitions_task (400 Query error: Unrecognized name: years_of_publication; Did you mean year_of_publication? at [5:25]

Location: us-west1
Job ID: airflow_Book_Recommendation_DAG_create_table_partitions_task_2024_03_26T01_49_19_111858_00_00_b15e6335484ec3e825412df4570fa29f
; 3265)
[2024-03-26T01:49:39.980+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-26T01:49:40.003+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
